### ISSUE TITLE
Can you provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [Beatusvir/vs-code-darcula#1]
Can you provide a grey Orange theme
[grey_orange.zip](https://github.com/Beatusvir/vs-code-darcula/files/5382188/grey_orange.zip)

**Comment by Beatusvir** [comment]
hey @jahnli , I created this theme a while ago, I just checked and it seems the way to create themes changed if you want please take a look at this [https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme](url)

**Comment by jahnli** [comment]
Can you help provide such a theme?Paid service is acceptable
